export async function generateReport(facility, uploadedData = null) {
  const { jsPDF } = await import("jspdf");

  let data;

  if (uploadedData) {
    data = uploadedData;
  } else {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/predict`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        datetime: new Date().toISOString(),
        facility_type: facility.facilityType || "hospital",
      }),
    });
    data = await res.json();
  }

  // Fetch model accuracy
  let accuracyText = "N/A";
  try {
    const accRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/accuracy/${facility.facilityType || "hospital"}`);
    const accData = await accRes.json();
    accuracyText = `${accData.accuracy_percent}% (MAE: ${accData.mae} kWh, MAPE: ${accData.mape}%)`;
  } catch (_) {}

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  function addPageHeader() {
    doc.setFillColor(45, 74, 45);
    doc.rect(0, 0, pageWidth, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("GridWise", 14, 18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Energy Prediction Report", 14, 28);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 35);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`Status: ${facility.status}`, pageWidth - 50, 28);
  }

  function addDivider(y) {
    doc.setDrawColor(200, 215, 195);
    doc.setLineWidth(0.5);
    doc.line(14, y, pageWidth - 14, y);
    return y + 10;
  }

  function addSectionTitle(title, y) {
    doc.setTextColor(45, 74, 45);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, 14, y);
    return y + 10;
  }

  function addFooters() {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(45, 74, 45);
      doc.rect(0, pageHeight - 15, pageWidth, 15, "F");
      doc.setFontSize(7);
      doc.setTextColor(200, 220, 200);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by GridWise Systems — AI-Powered Energy Prediction and Management", 14, pageHeight - 6);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 6, { align: "right" });
    }
  }

  addPageHeader();
  let y = 55;

  doc.setTextColor(45, 74, 45);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(facility.name, 14, y);
  y += 7;

  doc.setTextColor(120, 120, 120);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(facility.category.toUpperCase(), 14, y);
  y += 5;

  doc.setTextColor(100, 130, 100);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Report covers last 12 hours of actual consumption + next-hour prediction.",
    14, y
  );
  y += 10;

  y = addDivider(y);
  y = addSectionTitle("Energy Summary", y);

  const kpis = [
    ["Current Demand", `${data.current_demand_kwh} kWh`],
    ["Predicted Next-Hour Demand", `${data.predicted_next_hour_kwh} kWh`],
    ["Peak Load Risk", data.peak_load_risk],
    ["Renewable Mix", `${data.renewable_mix_percent}%`],
    ["Model Accuracy", accuracyText],
  ];

  kpis.forEach(([label, value]) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(label, 18, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 45, 30);
    doc.text(value, 130, y);
    y += 10;
  });

  y += 4;
  y = addDivider(y);
  y = addSectionTitle("AI Insights", y);

  data.insights.forEach((insight) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 6 + 3;
  });

  y += 4;
  y = addDivider(y);
  y = addSectionTitle("AI Recommendations", y);

  data.recommendations.forEach((rec) => {
    if (y > 250) {
      doc.addPage();
      addPageHeader();
      y = 55;
    }
    const priorityColors = { High: [180, 30, 30], Medium: [180, 120, 0], Low: [45, 74, 45] };
    const [r, g, b] = priorityColors[rec.priority] || [45, 74, 45];
    doc.setTextColor(r, g, b);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`[${rec.priority}] ${rec.title}`, 14, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(rec.impact, pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 6;
  });

  doc.addPage();
  addPageHeader();
  y = 55;

  y = addSectionTitle("Historical Energy Data (Last 12 Hours)", y);

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);
  doc.text("Last row shows next-hour prediction.", 14, y);
  y += 10;

  doc.setFillColor(45, 74, 45);
  doc.rect(14, y - 5, pageWidth - 28, 9, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Time", 18, y);
  doc.text("Actual (kWh)", 80, y);
  doc.text("Predicted (kWh)", 140, y);
  y += 10;

  data.chart.labels.forEach((label, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(248, 252, 248);
      doc.rect(14, y - 5, pageWidth - 28, 8, "F");
    }
    doc.setTextColor(60, 60, 60);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(label, 18, y);
    doc.text(String(data.chart.actual[i]), 80, y);
    doc.text(String(data.chart.predicted[i]), 140, y);
    y += 9;
  });

  const nextHour = new Date();
  nextHour.setHours(nextHour.getHours() + 1);
  const nextLabel = nextHour.toTimeString().slice(0, 5);

  doc.setFillColor(220, 240, 220);
  doc.rect(14, y - 5, pageWidth - 28, 8, "F");
  doc.setTextColor(45, 74, 45);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(`${nextLabel} (Next Hour)`, 18, y);
  doc.text("—", 80, y);
  doc.text(String(data.predicted_next_hour_kwh), 140, y);
  y += 12;

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);

  addFooters();
  doc.save(`GridWise_${facility.name.replace(/\s+/g, "_")}_Report.pdf`);
}
